# Generated by Django 3.1.1 on 2021-06-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='paradigm',
        ),
    ]
