# Generated by Django 3.1.1 on 2021-06-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0002_remove_language_paradigm'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='paradigm',
            field=models.CharField(default='Functional', max_length=50),
            preserve_default=False,
        ),
    ]
